Improve documentation on TotalScatteringReduction.
neutrons/mantid_total_scattering pull request #111
Opened 2021-10-01 20:28 UTC by wdzhou

This fixes [PD #381](https://code.ornl.gov/sns-hfir-scse/diffraction/powder/powder-diffraction/-/issues/381).

Improve documentation on method [TotalScatteringReduction](https://github.com/neutrons/mantid_total_scattering/blob/ff81e54073cd3f5419b73a459aa14987aac7b66b/total_scattering/reduction/total_scattering_reduction.py#L411)

2021-10-02 15:33 UTC, Kvieta1990 requested changes
Just some tiny issues and a bit further change request. Once those comments I put get addressed, I am pretty happy to approve the PR. Thank you!

2021-10-02 15:33 UTC, Kvieta1990 commented on total_scattering/reduction/total_scattering_reduction.py
> +    #   3. self scattering correction smd save S(Q) corrected
`smd`???

2021-10-02 15:33 UTC, Kvieta1990 commented on total_scattering/reduction/total_scattering_reduction.py
> +    # van       = van - ban_bg
what does `ban_bg` stand for? Do you mean `van_bg`?

2021-10-02 15:33 UTC, Kvieta1990 commented on total_scattering/reduction/total_scattering_reduction.py
> +    # Retrieve file names from 'config'
How about this?

```
# Figure out experimental runs either with run numbers
# and facility name or retrieve file name from 'config'
```

2021-10-02 15:33 UTC, Kvieta1990 commented on total_scattering/reduction/total_scattering_reduction.py
> +    #################################################################
We should fix the following line,

[https://github.com/neutrons/mantid_total_scattering/blob/370564bd97bcc94239a69c8b0065673164954b51/total_scattering/reduction/total_scattering_reduction.py#L1158](https://github.com/neutrons/mantid_total_scattering/blob/370564bd97bcc94239a69c8b0065673164954b51/total_scattering/reduction/total_scattering_reduction.py#L1158)

to become like this,

```
# Save (sample - back) /  van_corrected
```

2021-10-04 13:16 UTC, wdzhou commented on total_scattering/reduction/total_scattering_reduction.py
> +    #   3. self scattering correction smd save S(Q) corrected
and... column-shifted-typo

2021-10-04 13:17 UTC, wdzhou commented
@Kvieta1990 I've made changes according to your review.  Could you take a look again and merge this PR?  Thanks.

2021-10-04 13:44 UTC, Kvieta1990 approved these changes
Seems good to me!

2021-10-04 13:45 UTC, merged